resource_types:
- name: rss
  type: docker-image
  source:
    repository: doubtingben/rss
    tag:        latest

resources:
- name: ars-technica
  type: rss
  source:
    url: https://starkandwayne.com/blog/rss/

jobs:
- name: post ars technica news
  public: true
  plan:
    - get: ars-technica
      trigger: true

    - task: alert
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: echo
          args: ["I cant believe this works"]