---
platform: linux

resources:
  - name: back-channel-repo
    type: git
    source:
      uri: https://github.com/doubtingben/back-channel.git
      branch: master

image_resource:
  type: docker-image
  source:
    repository: golang:1.11-rc-stretch

inputs:
- name: back-channel-repo

outputs:
- name: back-channel-built

run:
  path: go
  args:
    - build